sonar.projectKey=festival-frontend
sonar.projectName=festival-frontend
sonar.issue.ignore.multicriteria=apiTypeAliases
sonar.issue.ignore.multicriteria.apiTypeAliases.ruleKey=typescript:S6564
sonar.issue.ignore.multicriteria.apiTypeAliases.resourceKey=**/api/types.ts
sonar.sources=apps,packages,scripts
sonar.exclusions=**/node_modules/**,**/.next/**,**/next-env.d.ts
