spring.mongodb.uri=mongodb://localhost:27017/festival

festival.security.secure-cookies=false
festival.security.login.page.base-url=http://localhost:3000
festival.security.login.page.client-secret=festival-page-local-secret
festival.security.login.admin.base-url=http://127.0.0.1:3001
festival.security.login.admin.client-secret=festival-admin-local-secret
festival.keycloak.realm-url=http://localhost:8181/realms/festival

festival.shop.checkout-enabled=true

festival.media.endpoint=http://localhost:3900
festival.media.region=garage
festival.media.bucket=festival-media
festival.media.access-key=GK0000000000000000000000de
festival.media.secret-key=feedfeedfeedfeedfeedfeedfeedfeedfeedfeedfeedfeedfeedfeedfeedfeed
festival.media.public-base-url=http://festival-media.web.localhost:3902

logging.level.com.vertyll.festival=DEBUG
