spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.ssl.bundle=internal-ca
spring.ssl.bundle.pem.internal-ca.truststore.certificate=${INTERNAL_CA_CERT}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.bundle=internal-ca

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

application.security.secure-cookies=true
application.security.login.page.base-url=${FESTIVAL_PAGE_URL}
application.security.login.page.client-secret=${KEYCLOAK_PAGE_CLIENT_SECRET}
application.security.login.admin.base-url=${FESTIVAL_ADMIN_URL}
application.security.login.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
application.keycloak.realm-url=${KEYCLOAK_REALM_URL}
application.mail.from=${MAIL_FROM}

application.shop.checkout-enabled=${FESTIVAL_CHECKOUT_ENABLED}

application.media.endpoint=${S3_ENDPOINT}
application.media.region=${S3_REGION}
application.media.bucket=${S3_BUCKET}
application.media.access-key=${S3_ACCESS_KEY}
application.media.secret-key=${S3_SECRET_ACCESS_KEY}
application.media.public-base-url=${S3_PUBLIC_BASE_URL}
application.media.ssl-bundle=internal-ca

logging.structured.format.console=ecs
